window.QUIZ_CATALOG = {
  riasec:{
    title:'Tes Minat Karier RIASEC',shortTitle:'Tes Karier',emoji:'🧩',colors:['#3b82f6','#06b6d4'],
    subtitle:'Temukan tiga lingkungan kerja yang paling sesuai dengan minatmu melalui enam tema karier Holland.',
    note:'Hasil menunjukkan kecenderungan minat, bukan menentukan satu profesi wajib. Gunakan tiga skor teratas sebagai bahan mengeksplorasi jurusan, peran, dan lingkungan kerja.',
    dimensions:{R:{name:'Realistic',preview:'Praktis dan teknis',color:'#f97316'},I:{name:'Investigative',preview:'Analitis dan penasaran',color:'#3b82f6'},A:{name:'Artistic',preview:'Kreatif dan ekspresif',color:'#a855f7'},S:{name:'Social',preview:'Membantu dan mengajar',color:'#ec4899'},E:{name:'Enterprising',preview:'Memimpin dan meyakinkan',color:'#eab308'},C:{name:'Conventional',preview:'Rapi dan sistematis',color:'#22c55e'}},
    questions:[
      {dimension:'R',text:'Saya menikmati pekerjaan yang melibatkan alat, mesin, atau kegiatan langsung.'},{dimension:'R',text:'Saya senang memperbaiki benda atau mencari cara praktis agar sesuatu berfungsi.'},{dimension:'R',text:'Saya lebih tertarik melihat hasil nyata daripada membahas konsep terlalu lama.'},
      {dimension:'I',text:'Saya menikmati proses menyelidiki penyebab suatu masalah.'},{dimension:'I',text:'Saya suka membaca data, menemukan pola, atau menguji sebuah dugaan.'},{dimension:'I',text:'Pertanyaan sulit membuat saya penasaran untuk mencari jawabannya.'},
      {dimension:'A',text:'Saya menikmati kegiatan yang memberi ruang untuk imajinasi dan ekspresi pribadi.'},{dimension:'A',text:'Saya tertarik membuat tulisan, visual, musik, konsep, atau pengalaman baru.'},{dimension:'A',text:'Saya lebih bersemangat saat tugas tidak memiliki hanya satu jawaban benar.'},
      {dimension:'S',text:'Saya merasa puas ketika dapat membantu orang berkembang atau memahami sesuatu.'},{dimension:'S',text:'Saya nyaman mendengarkan masalah dan memberi dukungan.'},{dimension:'S',text:'Saya tertarik pada pekerjaan yang berdampak langsung bagi orang lain.'},
      {dimension:'E',text:'Saya menikmati kesempatan memimpin, bernegosiasi, atau memengaruhi keputusan.'},{dimension:'E',text:'Saya bersemangat mengejar target dan menggerakkan orang menuju hasil.'},{dimension:'E',text:'Saya cukup nyaman mengambil risiko yang diperhitungkan untuk sebuah peluang.'},
      {dimension:'C',text:'Saya menyukai sistem, prosedur, dan informasi yang tertata jelas.'},{dimension:'C',text:'Saya teliti saat menangani jadwal, dokumen, angka, atau detail administratif.'},{dimension:'C',text:'Saya merasa nyaman jika tugas memiliki aturan dan standar keberhasilan yang jelas.'}
    ],
    profiles:{R:{emoji:'🛠️',title:'Practical Builder',tagline:'Kamu berkembang lewat tindakan, alat, dan hasil yang dapat dilihat.',insight:'Kamu cenderung menikmati tantangan konkret dan solusi yang langsung bisa diuji.',tip:'Eksplorasi bidang teknik, operasional, produksi, lapangan, atau pekerjaan berbasis keterampilan.'},I:{emoji:'🔬',title:'Curious Investigator',tagline:'Rasa ingin tahu dan analisis menjadi bahan bakar utamamu.',insight:'Kamu menikmati pertanyaan rumit, data, dan proses memahami cara sesuatu bekerja.',tip:'Coba proyek riset, data, teknologi, kesehatan, atau strategi yang menuntut analisis mendalam.'},A:{emoji:'🎨',title:'Creative Explorer',tagline:'Kamu membutuhkan ruang untuk mencipta dan mengekspresikan gagasan.',insight:'Kebebasan bereksperimen dan menghasilkan sesuatu yang orisinal terasa penting bagimu.',tip:'Bangun portofolio kecil di desain, konten, seni, tulisan, produk, atau bidang kreatif lain.'},S:{emoji:'🤲',title:'People Supporter',tagline:'Kamu menemukan makna lewat pertumbuhan dan kesejahteraan orang lain.',insight:'Interaksi yang hangat dan kesempatan membantu membuat pekerjaan terasa bernilai.',tip:'Eksplorasi pendidikan, konseling, layanan, komunitas, kesehatan, atau pengembangan manusia.'},E:{emoji:'📣',title:'Bold Initiator',tagline:'Kamu terdorong oleh peluang, pengaruh, dan hasil yang menantang.',insight:'Kamu cenderung nyaman mengambil inisiatif dan membawa orang menuju tujuan.',tip:'Coba penjualan, bisnis, kepemimpinan, pemasaran, negosiasi, atau pengelolaan proyek.'},C:{emoji:'📊',title:'System Organizer',tagline:'Keteraturan dan ketelitian membantumu menghasilkan kerja yang konsisten.',insight:'Kamu menikmati struktur yang jelas, data yang rapi, dan proses yang dapat diandalkan.',tip:'Eksplorasi keuangan, administrasi, quality assurance, analisis operasi, atau manajemen data.'}},
    sources:[{label:'O*NET Interest Profiler — U.S. Department of Labor',url:'https://www.onetcenter.org/IP.html'},{label:'Holland, J. L. — Making Vocational Choices'},{label:'RIASEC dipakai sebagai peta minat pendidikan dan pekerjaan, bukan tes kemampuan.'}]
  },
  growth:{
    title:'Quiz Growth Mindset',shortTitle:'Quiz Growth Mindset',emoji:'🌱',colors:['#f59e0b','#22c55e'],
    subtitle:'Lihat bagaimana kamu merespons tantangan, masukan, kesalahan, dan proses belajar.',
    note:'Growth mindset bukan tuntutan untuk selalu positif. Hasil ini membantu melihat pola belajar yang bisa dilatih, sambil tetap mengakui batas, konteks, dan kebutuhan istirahat.',
    dimensions:{CH:{name:'Menyambut Tantangan',preview:'Berani mencoba',color:'#f59e0b'},FB:{name:'Terbuka pada Masukan',preview:'Belajar dari feedback',color:'#3b82f6'},ER:{name:'Belajar dari Kesalahan',preview:'Pulih dan mengevaluasi',color:'#ec4899'},PR:{name:'Percaya pada Proses',preview:'Tekun bertumbuh',color:'#22c55e'}},
    questions:[
      {dimension:'CH',text:'Saya bersedia mencoba tugas baru meskipun belum yakin akan berhasil.'},{dimension:'CH',text:'Tantangan membuat saya ingin mencari strategi baru.'},{dimension:'CH',reverse:true,text:'Saya cenderung menghindari kegiatan yang bisa memperlihatkan kekurangan saya.'},{dimension:'CH',text:'Saya dapat memulai dari level pemula tanpa merasa malu.'},
      {dimension:'FB',text:'Saya bisa memisahkan kritik terhadap hasil kerja dari nilai diri saya.'},{dimension:'FB',text:'Masukan yang spesifik membantu saya melihat hal yang sebelumnya terlewat.'},{dimension:'FB',reverse:true,text:'Saya langsung defensif ketika cara kerja saya dikoreksi.'},{dimension:'FB',text:'Saya bersedia bertanya agar bisa memperbaiki hasil.'},
      {dimension:'ER',text:'Setelah gagal, saya mencoba memahami bagian mana yang perlu diubah.'},{dimension:'ER',text:'Kesalahan dapat memberi informasi berguna untuk percobaan berikutnya.'},{dimension:'ER',reverse:true,text:'Satu kegagalan mudah membuat saya merasa tidak berbakat.'},{dimension:'ER',text:'Saya dapat kembali mencoba setelah memberi diri waktu untuk pulih.'},
      {dimension:'PR',text:'Saya percaya kemampuan dapat meningkat melalui latihan yang tepat.'},{dimension:'PR',text:'Saya menghargai kemajuan kecil yang konsisten.'},{dimension:'PR',reverse:true,text:'Kalau tidak cepat mahir, saya menganggap bidang itu bukan untuk saya.'},{dimension:'PR',text:'Saya mau mengganti cara belajar ketika pendekatan lama tidak efektif.'}
    ],
    profiles:{CH:{emoji:'🧗',title:'Brave Beginner',tagline:'Kamu bertumbuh saat berani masuk ke wilayah yang belum dikuasai.',insight:'Kesediaan mencoba membantumu mengumpulkan pengalaman yang tidak bisa didapat hanya dari perencanaan.',tip:'Pilih satu tantangan kecil dengan tingkat kesulitan sedikit di atas kemampuanmu saat ini.'},FB:{emoji:'🪞',title:'Open Learner',tagline:'Masukan menjadi cermin untuk memperbaiki arah belajarmu.',insight:'Kamu cukup mampu melihat feedback sebagai informasi, bukan serangan pribadi.',tip:'Saat meminta masukan, tanyakan satu hal spesifik yang paling perlu diperbaiki.'},ER:{emoji:'🔄',title:'Reflective Rebuilder',tagline:'Kamu mampu mengubah kesalahan menjadi bahan untuk percobaan berikutnya.',insight:'Kekuatanmu ada pada evaluasi dan kemampuan kembali bergerak setelah hasil yang kurang baik.',tip:'Setelah kendala, catat: apa yang berhasil, apa yang tidak, dan satu perubahan berikutnya.'},PR:{emoji:'🌳',title:'Patient Grower',tagline:'Kamu percaya perubahan besar dibangun melalui proses yang konsisten.',insight:'Kesabaran dan kemauan mengubah strategi mendukung perkembangan jangka panjangmu.',tip:'Ukur progres dari perilaku yang bisa diulang, bukan hanya hasil akhir.'}},
    sources:[{label:'Dweck, C. S. — Mindset: The New Psychology of Success'},{label:'Yeager & Dweck (2020) — What Can Be Learned from Growth Mindset Controversies?',url:'https://doi.org/10.1037/amp0000794'},{label:'Quiz ini adalah refleksi edukatif dan bukan instrumen psikologis baku.'}]
  },
  emotion:{
    title:'Quiz Regulasi Emosi',shortTitle:'Quiz Emosi',emoji:'🌤️',colors:['#f97316','#ec4899'],
    subtitle:'Kenali cara kamu menyadari, menenangkan, mengekspresikan, dan memulihkan diri dari emosi yang kuat.',
    note:'Ini adalah alat refleksi kesejahteraan, bukan diagnosis kondisi psikologis. Skor rendah menunjukkan area yang dapat dilatih secara bertahap atau dibicarakan dengan tenaga profesional bila mengganggu keseharian.',
    dimensions:{AW:{name:'Kesadaran Emosi',preview:'Mengenali perasaan',color:'#f97316'},SO:{name:'Menenangkan Diri',preview:'Mengelola intensitas',color:'#3b82f6'},EX:{name:'Ekspresi Sehat',preview:'Menyampaikan dengan aman',color:'#ec4899'},RC:{name:'Pemulihan',preview:'Kembali seimbang',color:'#22c55e'}},
    questions:[
      {dimension:'AW',text:'Saya dapat memberi nama pada emosi yang sedang saya rasakan.'},{dimension:'AW',text:'Saya mengenali perubahan tubuh ketika emosi mulai meningkat.'},{dimension:'AW',reverse:true,text:'Saya sering baru sadar sedang kesal setelah bereaksi.'},{dimension:'AW',text:'Saya dapat membedakan marah, kecewa, takut, dan lelah.'},
      {dimension:'SO',text:'Saya punya cara aman untuk menurunkan intensitas emosi.'},{dimension:'SO',text:'Saya dapat mengambil jeda sebelum memberi respons saat tersulut.'},{dimension:'SO',reverse:true,text:'Saat emosi kuat muncul, saya merasa tidak punya pilihan selain mengikutinya.'},{dimension:'SO',text:'Saya tahu kegiatan apa yang membantu tubuh saya merasa lebih tenang.'},
      {dimension:'EX',text:'Saya mampu menyampaikan perasaan tanpa merendahkan diri sendiri atau orang lain.'},{dimension:'EX',text:'Saya dapat meminta dukungan dengan cukup jelas.'},{dimension:'EX',reverse:true,text:'Saya biasanya memendam semuanya sampai akhirnya meledak atau menarik diri.'},{dimension:'EX',text:'Saya bisa mengatakan bahwa saya butuh waktu sebelum melanjutkan percakapan.'},
      {dimension:'RC',text:'Setelah situasi emosional, saya dapat kembali ke rutinitas secara bertahap.'},{dimension:'RC',text:'Saya memberi diri waktu untuk pulih tanpa terus menyalahkan diri.'},{dimension:'RC',reverse:true,text:'Peristiwa kecil yang tidak menyenangkan merusak seluruh hari saya.'},{dimension:'RC',text:'Saya bisa mengambil pelajaran tanpa terus mengulang kejadian di kepala.'}
    ],
    profiles:{AW:{emoji:'🔎',title:'Emotion Observer',tagline:'Kekuatanmu ada pada kemampuan membaca apa yang terjadi di dalam diri.',insight:'Kesadaran yang baik memberi jeda antara emosi dan tindakan.',tip:'Gunakan kalimat sederhana: “Saya merasa…, karena…, dan saat ini saya membutuhkan…”.'},SO:{emoji:'🫧',title:'Steady Soother',tagline:'Kamu punya kemampuan menurunkan gelombang emosi sebelum bertindak.',insight:'Kamu cenderung dapat menciptakan ruang aman saat emosi meningkat.',tip:'Pertahankan dua strategi penenang yang mudah dilakukan dalam lima menit.'},EX:{emoji:'🗣️',title:'Clear Expresser',tagline:'Kamu cukup mampu mengubah emosi menjadi komunikasi yang dapat dipahami.',insight:'Ekspresi yang jelas membantu kebutuhanmu terlihat tanpa memperbesar konflik.',tip:'Sampaikan perasaan dan permintaan konkret tanpa menebak niat orang lain.'},RC:{emoji:'🌅',title:'Gentle Recoverer',tagline:'Kamu mampu kembali seimbang setelah melewati momen emosional.',insight:'Pemulihanmu didukung oleh penerimaan dan kemampuan kembali ke rutinitas.',tip:'Buat ritual transisi singkat setelah hari berat: minum, bergerak, mandi, atau menulis.'}},
    sources:[{label:'Gross, J. J. (1998) — The Emerging Field of Emotion Regulation Research',url:'https://doi.org/10.1037/1089-2680.2.3.271'},{label:'Gratz & Roemer (2004) — Difficulties in Emotion Regulation Scale',url:'https://doi.org/10.1023/B:JOBA.0000007455.08539.94'},{label:'Hasil bersifat reflektif dan non-diagnostik.'}]
  },
  social:{
    title:'Quiz Social Battery',shortTitle:'Quiz Social Battery',emoji:'🔋',colors:['#06b6d4','#8b5cf6'],
    subtitle:'Temukan situasi sosial yang mengisi energimu, yang mengurasnya, dan cara pulih yang paling pas.',
    note:'Social battery bukan label introvert atau ekstrovert yang mutlak. Energi sosial dapat berubah menurut orang, suasana, kesehatan, dan rasa aman.',
    dimensions:{SM:{name:'Kelompok Kecil',preview:'Hangat dan mendalam',color:'#06b6d4'},CR:{name:'Keramaian',preview:'Ramai dan dinamis',color:'#f97316'},ON:{name:'Waktu Sendiri',preview:'Pulih lewat ruang pribadi',color:'#8b5cf6'},NT:{name:'Koneksi Baru',preview:'Energik bertemu orang',color:'#ec4899'}},
    questions:[
      {dimension:'SM',text:'Percakapan mendalam dengan satu atau dua orang terasa mengisi energi saya.'},{dimension:'SM',text:'Saya lebih mudah menjadi diri sendiri dalam kelompok kecil.'},{dimension:'SM',text:'Saya menikmati pertemuan tenang yang memberi ruang semua orang berbicara.'},
      {dimension:'CR',text:'Suasana ramai sering membuat saya lebih bersemangat.'},{dimension:'CR',text:'Saya menikmati acara yang melibatkan banyak orang dan aktivitas.'},{dimension:'CR',reverse:true,text:'Keramaian hampir selalu membuat saya ingin segera pulang.'},
      {dimension:'ON',text:'Waktu sendirian membantu saya kembali jernih setelah banyak interaksi.'},{dimension:'ON',text:'Saya membutuhkan jeda tanpa percakapan agar energi saya pulih.'},{dimension:'ON',reverse:true,text:'Saya merasa makin lelah jika harus menghabiskan waktu sendirian.'},
      {dimension:'NT',text:'Bertemu orang baru biasanya membuat saya penasaran dan antusias.'},{dimension:'NT',text:'Saya cukup nyaman membuka percakapan di lingkungan baru.'},{dimension:'NT',reverse:true,text:'Saya menghindari perkenalan baru meskipun situasinya terasa aman.'}
    ],
    profiles:{SM:{emoji:'☕',title:'Cozy Connector',tagline:'Koneksi kecil yang hangat adalah sumber energi sosial terbesarmu.',insight:'Kualitas percakapan lebih berarti bagimu daripada jumlah orang di sekitar.',tip:'Pilih pertemuan kecil dan beri ruang untuk percakapan yang tidak terburu-buru.'},CR:{emoji:'🎊',title:'Crowd Charger',tagline:'Dinamika banyak orang sering membangkitkan semangatmu.',insight:'Kamu mendapat stimulasi positif dari suasana ramai dan aktivitas bersama.',tip:'Seimbangkan agenda sosial dengan jeda singkat agar energi tetap stabil.'},ON:{emoji:'🌙',title:'Quiet Recharger',tagline:'Ruang pribadi membantumu memproses hari dan memulihkan energi.',insight:'Kesendirian yang disengaja menjadi bagian penting dari keseimbangan sosialmu.',tip:'Jadwalkan waktu pulih setelah acara besar sebelum kalender kembali penuh.'},NT:{emoji:'👋',title:'Curious Mingler',tagline:'Orang dan lingkungan baru menyalakan rasa ingin tahumu.',insight:'Kamu cukup mudah memperoleh energi dari kemungkinan koneksi baru.',tip:'Gunakan kekuatan ini untuk menjembatani orang yang belum saling mengenal.'}},
    sources:[{label:'Cain, S. — Quiet: The Power of Introverts in a World That Cannot Stop Talking'},{label:'Big Five Extraversion memberi konteks akademis untuk kecenderungan energi sosial.'},{label:'Konsep “social battery” di sini dipakai sebagai metafora reflektif.'}]
  },
  procrastination:{
    title:'Quiz Pola Prokrastinasi',shortTitle:'Quiz Prokrastinasi',emoji:'⏳',colors:['#22c55e','#3b82f6'],
    subtitle:'Cari tahu pemicu utama penundaanmu dan langkah kecil yang paling realistis untuk mulai bergerak.',
    note:'Menunda tidak selalu berarti malas. Tugas yang kabur, emosi tidak nyaman, energi rendah, atau distraksi dapat membutuhkan solusi yang berbeda.',
    dimensions:{PF:{name:'Takut Tidak Sempurna',preview:'Tertekan oleh standar',color:'#ec4899'},CL:{name:'Tugas Tidak Jelas',preview:'Sulit menentukan awal',color:'#3b82f6'},EN:{name:'Energi Rendah',preview:'Kapasitas sedang turun',color:'#f97316'},DS:{name:'Mudah Terdistraksi',preview:'Perhatian cepat berpindah',color:'#22c55e'}},
    questions:[
      {dimension:'PF',text:'Saya menunda karena khawatir hasilnya tidak cukup bagus.'},{dimension:'PF',text:'Saya sulit memulai jika belum menemukan cara terbaik.'},{dimension:'PF',text:'Standar tinggi membuat tugas terasa lebih berat daripada seharusnya.'},{dimension:'PF',reverse:true,text:'Saya nyaman membuat draf buruk sebagai langkah pertama.'},
      {dimension:'CL',text:'Saya menunda ketika tidak tahu langkah pertama yang harus dilakukan.'},{dimension:'CL',text:'Tugas besar terasa kabur sampai saya memecahnya menjadi bagian kecil.'},{dimension:'CL',text:'Saya kehilangan waktu karena terus menentukan prioritas.'},{dimension:'CL',reverse:true,text:'Saya mudah mengubah tugas besar menjadi tindakan berikutnya yang jelas.'},
      {dimension:'EN',text:'Saya sering menunda karena tubuh atau pikiran sudah kelelahan.'},{dimension:'EN',text:'Tugas sederhana terasa berat ketika jadwal saya terlalu padat.'},{dimension:'EN',text:'Saya memaksakan bekerja pada waktu ketika energi saya biasanya rendah.'},{dimension:'EN',reverse:true,text:'Saya cukup baik menyesuaikan jenis tugas dengan tingkat energi.'},
      {dimension:'DS',text:'Notifikasi atau aplikasi lain mudah mengalihkan saya dari tugas.'},{dimension:'DS',text:'Saya membuka banyak hal baru sebelum menyelesaikan yang sedang dikerjakan.'},{dimension:'DS',text:'Lingkungan yang ramai membuat saya sulit bertahan pada satu pekerjaan.'},{dimension:'DS',reverse:true,text:'Saya dapat melindungi waktu fokus dari gangguan yang bisa dicegah.'}
    ],
    profiles:{PF:{emoji:'📝',title:'Perfectionist Delayer',tagline:'Keinginan menghasilkan yang terbaik kadang membuat langkah pertama terasa terlalu berat.',insight:'Tekanan standar lebih sering menghambat daripada kekurangan niat.',tip:'Buat versi 20% yang sengaja belum sempurna, lalu jadwalkan waktu khusus untuk memperbaikinya.'},CL:{emoji:'🧭',title:'Foggy Starter',tagline:'Kamu lebih mudah bergerak ketika tujuan berubah menjadi langkah yang sangat jelas.',insight:'Ketidakjelasan tugas adalah hambatan utama, sehingga perencanaan singkat memberi dampak besar.',tip:'Tulis satu tindakan fisik yang bisa dilakukan dalam lima menit, misalnya membuka dokumen dan membuat tiga judul.'},EN:{emoji:'🪫',title:'Energy-Limited Planner',tagline:'Penundaanmu sering menjadi sinyal bahwa kapasitas sedang menipis.',insight:'Energi dan beban harian perlu diperhitungkan sebelum menuntut motivasi lebih.',tip:'Pindahkan tugas berat ke jam energi terbaik dan kecilkan target pada hari dengan kapasitas rendah.'},DS:{emoji:'📵',title:'Distracted Jumper',tagline:'Perhatianmu mudah direbut oleh hal yang lebih cepat memberi rangsangan.',insight:'Lingkungan fokus akan lebih membantu daripada mengandalkan kemauan setiap saat.',tip:'Coba satu sesi 20 menit dengan satu tab, ponsel di luar jangkauan, dan tujuan yang spesifik.'}},
    sources:[{label:'Steel, P. (2007) — The Nature of Procrastination',url:'https://doi.org/10.1037/0033-2909.133.1.65'},{label:'Sirois & Pychyl — Procrastination, Health, and Well-Being'},{label:'Quiz mengidentifikasi pola reflektif, bukan diagnosis gangguan perhatian.'}]
  },
  money:{
    title:'Quiz Money Personality',shortTitle:'Quiz Keuangan',emoji:'💰',colors:['#eab308','#f97316'],
    subtitle:'Kenali kecenderunganmu saat membelanjakan, menyimpan, merencanakan, dan menikmati uang.',
    note:'Hasil menggambarkan kebiasaan dan preferensi, bukan nasihat investasi atau penilaian kondisi finansial. Situasi pendapatan dan tanggungan tetap perlu dilihat secara nyata.',
    dimensions:{SV:{name:'Penjaga Dana',preview:'Aman lewat simpanan',color:'#22c55e'},SP:{name:'Penikmat Momen',preview:'Uang untuk pengalaman',color:'#f97316'},PL:{name:'Perencana',preview:'Suka tujuan dan anggaran',color:'#3b82f6'},GV:{name:'Pemberi',preview:'Senang berbagi',color:'#ec4899'}},
    questions:[
      {dimension:'SV',text:'Saya merasa lebih tenang ketika memiliki dana cadangan.'},{dimension:'SV',text:'Saya cenderung mempertimbangkan kebutuhan masa depan sebelum membeli.'},{dimension:'SV',reverse:true,text:'Saya jarang memikirkan sisa uang setelah melakukan pembelian.'},{dimension:'SV',text:'Menabung memberi saya rasa aman.'},
      {dimension:'SP',text:'Saya senang memakai uang untuk pengalaman yang membuat hidup lebih berwarna.'},{dimension:'SP',text:'Saya cukup spontan membeli sesuatu yang terasa menyenangkan.'},{dimension:'SP',text:'Saya melihat uang sebagai alat untuk menikmati hidup saat ini.'},{dimension:'SP',reverse:true,text:'Saya hampir selalu menolak pengeluaran yang hanya bertujuan memberi kesenangan.'},
      {dimension:'PL',text:'Saya suka menentukan tujuan keuangan yang jelas.'},{dimension:'PL',text:'Saya ingin tahu ke mana uang saya pergi setiap bulan.'},{dimension:'PL',text:'Anggaran membantu saya mengambil keputusan dengan lebih tenang.'},{dimension:'PL',reverse:true,text:'Saya merasa pencatatan uang tidak banyak berguna.'},
      {dimension:'GV',text:'Saya senang menggunakan uang untuk membantu atau membahagiakan orang lain.'},{dimension:'GV',text:'Memberi hadiah terasa lebih memuaskan daripada membeli sesuatu untuk diri sendiri.'},{dimension:'GV',text:'Saya mudah menawarkan bantuan finansial kepada orang yang saya sayangi.'},{dimension:'GV',reverse:true,text:'Saya hampir tidak pernah memasukkan kegiatan berbagi dalam rencana pengeluaran.'}
    ],
    profiles:{SV:{emoji:'🏦',title:'Safety Saver',tagline:'Rasa aman adalah nilai utama dalam keputusan keuanganmu.',insight:'Kamu cenderung memikirkan perlindungan masa depan sebelum kenyamanan sesaat.',tip:'Tetapkan batas simpanan yang cukup agar keamanan tidak berubah menjadi rasa bersalah saat menikmati uang.'},SP:{emoji:'🎟️',title:'Experience Spender',tagline:'Kamu melihat uang sebagai jalan untuk menikmati hidup dan menciptakan pengalaman.',insight:'Pengeluaran terasa bermakna ketika memberi kesenangan atau kenangan.',tip:'Sediakan pos “bebas dinikmati” agar spontanitas tetap punya batas yang nyaman.'},PL:{emoji:'📒',title:'Purposeful Planner',tagline:'Tujuan dan struktur membuatmu lebih tenang saat mengelola uang.',insight:'Kamu suka memahami arus uang dan menghubungkannya dengan rencana.',tip:'Gunakan sistem sederhana dengan tiga pos utama agar perencanaan tidak terasa seperti pekerjaan tambahan.'},GV:{emoji:'🎁',title:'Generous Giver',tagline:'Berbagi menjadi salah satu cara terpentingmu memberi makna pada uang.',insight:'Kamu mendapatkan kepuasan saat sumber daya dapat membantu orang lain.',tip:'Buat batas berbagi yang jelas supaya kemurahan hati tetap selaras dengan kebutuhanmu sendiri.'}},
    sources:[{label:'Klontz et al. — Money Beliefs and Financial Behaviors'},{label:'OECD/INFE Toolkit for Measuring Financial Literacy and Inclusion',url:'https://www.oecd.org/financial/education/2022-INFE-Toolkit-Measuring-Finlit-Financial-Inclusion.pdf'},{label:'Hasil bukan saran investasi, kredit, atau keputusan finansial profesional.'}]
  },
  groupchat:{
    title:'Quiz Role di Grup Chat',shortTitle:'Quiz Grup Chat',emoji:'💬',colors:['#f43f5e','#8b5cf6'],
    subtitle:'Kalau grup chat adalah sebuah tim, peran apa yang paling sering kamu mainkan?',
    note:'Quiz ini dibuat untuk hiburan dan bahan obrolan. Jawab berdasarkan kebiasaanmu di grup yang paling aktif.',
    dimensions:{ST:{name:'Pemantik Obrolan',preview:'Selalu punya topik',color:'#f43f5e'},MM:{name:'Pemasok Meme',preview:'Menjaga suasana',color:'#f97316'},SR:{name:'Pembaca Senyap',preview:'Hadir tanpa ramai',color:'#8b5cf6'},MD:{name:'Penengah Grup',preview:'Merawat harmoni',color:'#06b6d4'}},
    questions:[
      {dimension:'ST',text:'Saya sering menjadi orang pertama yang memulai obrolan di grup.'},{dimension:'ST',text:'Kalau grup sepi, saya merasa ingin melempar topik baru.'},{dimension:'ST',text:'Saya sering mengajak anggota grup membuat rencana bersama.'},
      {dimension:'MM',text:'Saya punya stok meme, video, atau stiker untuk hampir setiap situasi.'},{dimension:'MM',text:'Saya suka mencairkan suasana grup dengan humor.'},{dimension:'MM',text:'Respons andalan saya sering berupa gambar, GIF, atau emoji.'},
      {dimension:'SR',text:'Saya membaca sebagian besar pesan meskipun jarang membalas.'},{dimension:'SR',text:'Saya baru muncul ketika ada topik yang benar-benar menarik.'},{dimension:'SR',text:'Saya merasa tetap dekat dengan grup walaupun lebih sering menyimak.'},
      {dimension:'MD',text:'Saya biasanya membantu meluruskan salah paham di grup.'},{dimension:'MD',text:'Saya memperhatikan jika ada anggota yang tertinggal atau tidak diajak.'},{dimension:'MD',text:'Saat obrolan memanas, saya mencoba menjaga suasana tetap nyaman.'}
    ],
    profiles:{ST:{emoji:'📣',title:'The Conversation Starter',tagline:'Grup hidup karena kamu selalu punya pintu masuk untuk ngobrol.',insight:'Energi dan inisiatifmu membuat orang lain lebih mudah ikut terlibat.',tip:'Sesekali lempar pertanyaan yang memberi ruang anggota pendiam untuk ikut masuk.'},MM:{emoji:'😂',title:'The Meme Supplier',tagline:'Kamu adalah departemen hiburan tidak resmi di grup.',insight:'Humormu membantu grup tetap hangat bahkan ketika semua orang sedang sibuk.',tip:'Simpan satu meme pamungkas untuk momen ketika grup benar-benar membutuhkannya.'},SR:{emoji:'👀',title:'The Silent Reader',tagline:'Jarang terlihat, tetapi hampir selalu tahu apa yang sedang terjadi.',insight:'Kehadiranmu tenang dan selektif; kamu berbicara ketika memang ada yang ingin disampaikan.',tip:'Satu reaksi kecil sesekali cukup untuk memberi tahu teman bahwa kamu tetap hadir.'},MD:{emoji:'🕊️',title:'The Group Mediator',tagline:'Kamu menjaga grup tetap nyaman, adil, dan saling terhubung.',insight:'Kepekaanmu pada suasana membuat banyak orang merasa lebih aman di dalam grup.',tip:'Ingat bahwa kamu juga boleh mundur dan tidak selalu bertanggung jawab atas suasana semua orang.'}},
    sources:[{label:'Quiz hiburan; tidak menggunakan instrumen psikologi klinis.'},{label:'Hasil dirancang sebagai pemantik percakapan dan dapat berubah di grup yang berbeda.'}]
  }
};
