name: Deploy to VPS

on:
  push:
    branches:
      - main # Ubah ini jika branch utama Anda bukan 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }} # Biasanya 22
          script: |
            # Arahkan ke folder project di VPS Anda. 
            # Sesuaikan "/path/to/your/project" dengan path yang benar di VPS.
            cd /path/to/your/project/Quizzy
            
            # Tarik pembaruan terbaru dari GitHub
            git pull origin main
            
            # Masuk ke folder app dan jalankan Docker Compose
            cd app
            docker-compose up -d --build
